---
# 本地 nginx 压缩包上传到服务器并解压, 
# 需要目标服务器有 gtar/unzip 命令
- name: extract nginx.tar.gz into /usr/local/src
  unarchive:
    src: ../files/nginx-1.12.2.tar.gz
    dest: /usr/local/src

# 环境检测

# 创建用户组和用户
# 不知道为什么 script 模块没法用, 以后再看
- name: create group and user if not exist
  copy: 
    src: /home/ubuntu/app/server-env/script/add_nginx_user.sh
    dest: /home/ubuntu/.ansible/tmp/scripts/
- name: change the mode of nginx script
  command: chmod -R 700 /home/ubuntu/.ansible/tmp/scripts/add_nginx_user.sh
- name: run the script to create nginx user
  command: /home/ubuntu/.ansible/tmp/scripts/add_nginx_user.sh

# 编译 nginx
# - name: compile nginx
#  shell: 

