---
# 本地 nginx 压缩包上传到服务器并解压, 
# 需要目标服务器有 gtar/unzip 命令
- name: "extract nginx.tar.gz into {{ install_src_dir }}"
  unarchive:
    src: "{{ dest_dir }}roles/nginx/files/nginx-1.12.2.tar.gz"
    dest: "{{ install_src_dir }}"

# 创建用户组和用户
# 不知道为什么 script 模块没法用, 以后再看
- name: create group and user if not exist
  copy: 
    src: "{{ local_dir }}scripts/add_nginx_user.sh"
    dest: "{{ dest_dir }}.ansible/tmp/scripts/"
- name: change the mode of nginx script
  file: 
    path: "{{ dest_dir }}.ansible/tmp/scripts/add_nginx_user.sh"
    mode: 0700
- name: run the script to create nginx user
  command: "{{ dest_dir }}.ansible/tmp/scripts/add_nginx_user.sh"

# 编译 nginx
# - name: clean makefile
#   command: make clean
#   args:
#     chdir: /usr/local/src/nginx-1.12.2
- name: execute configure
  command: >
    ./configure
    --prefix={{ install_dir }}nginx
    --pid-path={{ install_dir }}nginx/run/nginx.pid
    --with-http_ssl_module
    --with-pcre
    --user=nginx
    --group=nginx
  args:
    chdir: "{{ install_src_dir }}nginx-1.12.2"
- name: execute make
  command: make
  args:
    chdir: "{{ install_src_dir }}nginx-1.12.2"
- name: execute make install
  command: make install
  args:
    chdir: "{{ install_src_dir }}nginx-1.12.2"

# nginx 加入进程管理, for ubuntu
- name: copy nginx script to init.d
  copy: 
    src: "{{ dest_dir }}roles/nginx/scripts/scripts/nginx"
    dest: /etc/init.d
- name: add execute perm
  file:
    path: /etc/init.d/nginx
    mode: 0755

# 开机自启
- name: config start nginx when boot machine
  command: sysv-rc-conf nginx on

# 启动 nginx
- name: start nginx
  command: /etc/init.d/nginx start