---
# 本地 nginx 压缩包上传到服务器并解压, 
# 需要目标服务器有 gtar/unzip 命令
- name: "extract nginx.tar.gz into {{ install_src_path }}"
  unarchive:
    src: "{{ project_path }}roles/nginx/files/nginx-1.12.2.tar.gz"
    dest: "{{ install_src_path }}"

# 创建用户组和用户
# 不知道为什么 script 模块没法用, 以后再看
- name: create group and user if not exist
  copy: 
    src: "{{ project_path }}scripts/add_nginx_user.sh"
    dest: "{{ dest_path }}.ansible/tmp/scripts/"
- name: change the mode of nginx script
  file: 
    path: "{{ dest_path }}.ansible/tmp/scripts/add_nginx_user.sh"
    mode: 0700
- name: run the script to create nginx user
  command: "{{ dest_path }}.ansible/tmp/scripts/add_nginx_user.sh"

# 编译 nginx
# - name: clean makefile
#   command: make clean
#   args:
#     chdir: /usr/local/src/nginx-1.12.2
- name: execute configure
  command: >
    ./configure
    --prefix={{ install_path }}nginx
    --pid-path={{ install_path }}nginx/run/nginx.pid
    --with-http_ssl_module
    --with-pcre
    --user=nginx
    --group=nginx
  args:
    chdir: "{{ install_src_path }}nginx-1.12.2"
- name: execute make
  command: make
  args:
    chdir: "{{ install_src_path }}nginx-1.12.2"
- name: execute make install
  command: make install
  args:
    chdir: "{{ install_src_path }}nginx-1.12.2"

# nginx 加入进程管理, for ubuntu
- name: copy nginx script to init.d
  copy: 
    src: "{{ project_path }}roles/nginx/scripts/nginx"
    dest: /etc/init.d
- name: add execute perm
  file:
    path: /etc/init.d/nginx
    mode: 0755

# 开机自启
- name: config start nginx when boot machine
  command: sysv-rc-conf nginx on

# 创建配置文件路径
- name: modify config
  shell: "test -d {{ install_path }}nginx/conf/conf.d || mkdir {{ install_path }}nginx/conf/conf.d"

# 复制主配置文件
- name: copy nginx.conf
  copy:
    src: "{{ project_path }}roles/nginx/files/conf/nginx.conf"
    dest: "{{ install_path }}nginx/conf"

# 复制默认服务配置文件
- name: copy default server
  copy:
    src: "{{ project_path }}roles/nginx/files/conf/default.conf"
    dest: "{{ install_path }}nginx/conf/conf.d"

# 启动 nginx
- name: start nginx
  command: /etc/init.d/nginx start

# 创建服务器目录
- name: create server direct
  shell: test -d /home/www || mkdir /home/www
- name: create test file
  copy: 
    src: "{{ project_path }}roles/nginx/files/index.html"
    dest: /home/www