---
  # 安装依赖

  # 拷贝脚本到目标机器
  - name: copy dependence script to dest machine
    copy: 
      src: "{{ local_dir }}scripts/dependence.sh"
      dest: "{{ dest_dir }}.ansible/tmp/scripts/"

  - name: change mode
    file: 
      path: "{{ dest_dir }}.ansible/tmp/scripts/dependence.sh"
      mode: 0700

  - name: execute dependence script
    command: "{{ dest_dir }}.ansible/tmp/scripts/dependence.sh"