---
  # 安装依赖

  # 拷贝脚本到目标机器
  - name: copy dependence script to dest machine
    copy: 
      src: /home/ubuntu/app/server-env/scripts/dependence.sh
      dest: /home/ubuntu/.ansible/tmp/scripts/

  - name: change mode
    file: 
      path: /home/ubuntu/.ansible/tmp/scripts/dependence.sh
      mode: 0700

  - name: execute dependence script
    command: /home/ubuntu/.ansible/tmp/scripts/dependence.sh