---
  # 安装依赖

  # 替换 apt 源
  - name: backup apt source list
    raw: sudo cp /etc/apt/sources.list /etc/apt/sources.list.backup

  - name: copy apt source list to dest
    copy: 
      src: "{{ project_path }}files/apt/sources.list"
      dest: /etc/apt/sources.list

  - name: apt update
    shell: apt -y update

  # 拷贝脚本到目标机器
  - name: copy dependence script to dest machine
    copy: 
      src: "{{ project_path }}scripts/dependence.sh"
      dest: "{{ dest_path }}.ansible/tmp/scripts/"

  - name: change mode
    file: 
      path: "{{ dest_path }}.ansible/tmp/scripts/dependence.sh"
      mode: 0700

  - name: execute dependence script
    command: "{{ dest_path }}.ansible/tmp/scripts/dependence.sh"

  # bison 使用安装工具没法安装合适版本, 所以编译安装
  # @todo 这里需要分离出来
  - name: bison
    unarchive:
      src: "{{ project_path }}files/bison-2.7.tar.xz"
      dest: "{{ install_src_path }}"

  - name: execute bison's configure
    command: ./configure --prefix=/usr/local/
    args:
      chdir: "{{ install_src_path }}bison-2.7"

  - name: make bison
    command: make
    args:
      chdir: "{{ install_src_path }}bison-2.7"

  - name: make install
    command: make install
    args:
      chdir: "{{ install_src_path }}bison-2.7"