---
- name: apt-get install software-properties-common 
  command: apt-get install -y software-properties-common
- name: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
  command: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
- name: add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mariadb.mirror.rafal.ca/repo/10.2/ubuntu xenial main'
  command: add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mariadb.mirror.rafal.ca/repo/10.2/ubuntu xenial main'
- name: apt update
  command: apt update
- name: apt install mariadb-server
  command: apt install -y mariadb-server